[package]
name = "Dreamscript"
version = "1.0.0"
authors = []

[addresses]
puzzle_addr='0x43337ce1e45b1cd4812f24c84c4022a151dd9c217b423b97a105869d0427a59f'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
